# Generated by Django 5.1.7 on 2026-04-08 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, help_text='Field key → extracted value. Null for failed extractions.', null=True)),
                ('extraction_status', models.CharField(choices=[('DONE', 'Done'), ('FAILED', 'Failed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloudinary_public_id', models.CharField(max_length=512, unique=True)),
                ('storage_url', models.URLField(blank=True, help_text='Set after Cloudinary webhook confirms upload.', max_length=1024, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('IMAGE', 'Image')], max_length=10)),
                ('raw_text', models.TextField(blank=True, help_text='Extracted raw text. V2 delta extraction hook — do not remove.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('bytes', models.PositiveIntegerField(blank=True, help_text='File size in bytes, set from Cloudinary webhook.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
