# Generated by Django 5.1.7 on 2026-04-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedrow',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_rows', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='file',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='extractedrow',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_row', to='files.file'),
        ),
    ]
