# Generated by Django 5.1.7 on 2026-04-08 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fields_snapshot', models.JSONField(help_text='Frozen field configuration. Immutable after creation.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('done_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
